[package]
name = "mosaic"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.29.0"
#tui-textarea = { version = "0.7.0", features = ["search"] }
ropey = "1.6.1"
regex = "1.12.2"